# Generated by Django 3.2.6 on 2021-08-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'estoque', 'verbose_name_plural': 'estoques'},
        ),
    ]
