# Generated by Django 3.2.6 on 2021-08-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={},
        ),
    ]
