# Generated by Django 3.2.6 on 2021-08-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_estoque_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='estoque.estoque'),
        ),
    ]
