# Generated by Django 3.2.6 on 2021-09-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_estoqueitens_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.estoque'),
        ),
    ]
