# Generated by Django 3.2.6 on 2021-08-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20210828_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
