# Generated by Django 3.2.6 on 2021-08-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20210828_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='Funcionario',
            new_name='funcionario',
        ),
    ]
