# Generated by Django 3.2.6 on 2021-10-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('estoque', '0008_alter_estoqueitens_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='produto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='saldo',
            field=models.PositiveIntegerField(),
        ),
    ]
