# Generated by Django 3.2.6 on 2021-08-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_alter_estoqueitens_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoqueitens',
            options={'ordering': ('pk',)},
        ),
    ]
